# config file for running 10x pipeline 

RAW_DATA:
    "/beevol/home/riemondy/Projects/sc_repos/medulloblast/data/raw_data/190503_A00405_0099_AHK5MCDSXX"

DATA:
    "/beevol/home/riemondy/Projects/sc_repos/medulloblast/data/cellranger/"

PROJECT:
    "vibhakar"

TRANSCRIPTOME:
    "/beevol/home/riemondy/Projects/shared_dbases/cell_ranger/refdata-cellranger-GRCh38-3.0.0"

SAMPLES:
    - "1202_2"
    - "1226_4"
    - "1238_5"
    - "1397_6"
    - "1416_7"
    - "1433_8"

EXPT_GROUPS:
    - Foreman_1125,Foreman_1128

LSF_TEMPLATE:
    "lsf.template"

MAX_10X_JOBS: 24
