# config file for running 10x pipeline 

RAW_DATA:
    "/beevol/home/riemondy/Projects/sc_repos/vibhakar/data/raw_data/190104_A00405_0075_AHGWCWDSXX"

DATA:
    "/beevol/home/riemondy/Projects/sc_repos/vibhakar/data/cellranger/"

PROJECT:
    "vibhakar"

TRANSCRIPTOME:
    "/beevol/home/riemondy/Projects/shared_dbases/cell_ranger/refdata-cellranger-GRCh38-3.0.0"

SAMPLES:
    - "1_943"

EXPT_GROUPS:
    - 2_1008,4_1355

LSF_TEMPLATE:
    "lsf.template"

MAX_10X_JOBS: 24 
