# config file for running 10x pipeline 

RAW_DATA:
    "/beevol/home/riemondy/Projects/sc_repos/medulloblast/data/raw_data/190124_A00405_0079_AHFKMVDSXX"

DATA:
    "/beevol/home/riemondy/Projects/sc_repos/medulloblast/data/cellranger/"

PROJECT:
    "vibhakar"

TRANSCRIPTOME:
    "/beevol/home/riemondy/Projects/shared_dbases/cell_ranger/refdata-cellranger-GRCh38-3.0.0"

SAMPLES:
    - "1_925_010819"
    - "2_945_010819"
    - "3_1130_010819"
    - "4_1167_010819"

EXPT_GROUPS:
    - 1_925_010819,2_945_010819,3_1130_010819,4_1167_010819

LSF_TEMPLATE:
    "lsf.template"

MAX_10X_JOBS: 24 
